### ISSUE TITLE
Can not make kernel

### ISSUE THREAD

**Issue by pril** [mindboards/ev3sources#16]
Hello,

I'm trying to make the kernel, but it doesn't work. I can make lms2012,modules, programs, u-boot, doc and clean. If I starting to make the kernel I've got an error by the creation of advansys.c. I'll hope you can help me. 
![bildschirmfoto 2013-09-06 um 11 32 03](https://f.cloud.github.com/assets/794141/1094899/e0323652-16d7-11e3-8bfd-c85f7bec17f8.png)
![bildschirmfoto 2013-09-06 um 11 33 06](https://f.cloud.github.com/assets/794141/1094900/e2dd20b0-16d7-11e3-827b-3872c3de2097.png)
I'm currently working with the Ubuntu v. 12.03
![bildschirmfoto 2013-09-06 um 11 40 56](https://f.cloud.github.com/assets/794141/1094927/7b0918c6-16d8-11e3-9f82-04a270b09584.png)

**Comment by botbench** [comment]
Is this done using the 'make kernel' command in open_first?

**Comment by dlech** [comment]
I just built it successfully last night, so I think it is something with your system or setup. The only thing different that I can tell is that I am on Mint 15 (Ubuntu 13.04) and that I have renamed the `ev3sources` directory to `projects`.

I don't think the OS version should matter because it is using the toolchain and sources from the repo. The directory name though might be a factor. The original source code from LEGO has lots of stuff hard coded to `~/projects`.

**Comment by dlech** [comment]
Never mind about my previous response, I just tried it and it will build with the source in `~/ev3sources`. Looking through the make output though, mine does not attempt to compile `scsi/dirvers/advansys.c`. Have you tried editing your kernel configuration in `LEGOBoard.config`? You can run `git status` to see if it has been changed.

**Comment by pril** [comment]
Well, I'll try your recommended sugesstions tomorrow. 

 Yes, I used  'make kernel'. I've created a symbolic softlink for ev3source, known as project. Actually I don't edit my configuration, but I'll have a look at it tomorrow. 

Thank you for your quick respond to my questioning.
